version: "3.7"
services:
  # mongodb_container:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db
    # restart: unless-stopped
  client:
    build: 
      context: client
      dockerfile: Dockerfile
    restart: unless-stopped
    # links:
    #   - mongodb_container
    ports:
      - "5001:5000"
    volumes:
      - ./client:/app
    environment:
      - IS_DOCKER=Yes
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    restart: unless-stopped
    # links:
    #   - mongodb_container
    volumes:
      - ./:/usr/src/app
    ports:
      - "5002:5000"
    environment:
      - IS_DOCKER=Yes
  # resume_parser:
  #   build:
  #     context: resume_parser
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   links:
  #     - mongodb_container
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "5003:5000"
  nginx:
    image: nginx:alpine
    ports:
      - "5050:5050"
    volumes:
      - ./gateway/nginx_config.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - client
      - auth
# volumes:
#   mongodb_data_container