export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_UPLOAD_RESUME = "SET_UPLOAD_RESUME";
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS_RESUME';
export const SUCCESS_UPLOAD_FILE = 'SUCCESS_UPLOAD_RESUME';
export const FAILURE_UPLOAD_FILE = 'FAILURE_UPLOAD_RESUME';